name: Simple-Web-Deployment

on:
  workflow_dispatch:

jobs:

  Build-Deploy:
  
    runs-on: ubuntu-latest
    
    steps:

# ~~~~~~~~~~~~~~~~~~~ Dumping Code ~~~~~~~~~~~~~~~~~~~
    
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Building Docker Images
      run: |
        docker image build -t simple-web-app:${{ github.sha }} . 
        docker image tag simple-web-app:${{ github.sha }} ${{secrets.DOCKER_REPO}}/simple-web-app:${{ github.sha }}
        docker image tag simple-web-app:${{ github.sha }} ${{secrets.DOCKER_REPO}}/simple-web-app:latest  

    - name: Pushing Image onto Docker Hub
      run: |
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
        docker images
        docker image push ${{secrets.DOCKER_REPO}}/simple-web-app:${{ github.sha }}
        docker image push ${{secrets.DOCKER_REPO}}/simple-web-app:latest
